
from django.urls import path
from . import views, nodeviews, todoviews
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard/client', views.client_dashboard, name='client_dashboard'),
    path('dashboard/admin', views.admin_dashboard, name='admin_dashboard'),
    # API Endpoints
    path('api/admin/create-client/', views.api_create_client, name='api_create_client'),
    path('api/admin/clients/', views.api_get_clients, name='api_get_clients'),
    path('api/admin/create-subscription/', views.api_create_subscription, name='api_create_subscription'),
    path('api/admin/subscriptions/', views.api_get_subscriptions, name='api_get_subscriptions'),
    path('api/admin/subscription-options/', views.api_subscription_options, name='api_subscription_options'),
    path('api/admin/create-hosting-plan/', views.api_create_hosting_plan, name='api_create_hosting_plan'),
    path('api/admin/update-hosting-plan/', views.api_update_hosting_plan, name='api_update_hosting_plan'),
    path('api/admin/hosting-plans/', views.api_get_hosting_plans, name='api_get_hosting_plans'),
    path('api/admin/create-addon/', views.api_create_addon, name='api_create_addon'),
    path('api/admin/update-addon/', views.api_update_addon, name='api_update_addon'),
    path('api/admin/addons/', views.api_get_addons, name='api_get_addons'),
    path('api/hosting/plans/', views.hosting_plans, name='hosting_plans'),
    path('api/contact/', views.contact, name='contact'),
    path('main', views.main, name='main'),
    path('addtobalance', views.addtobalance, name='addtobalance'),
    path('outbalance', views.outbalance, name='outbalance'),
    path('activities', views.activities, name='activities'),
    path('createactivity', views.createactivity, name='createactivity'),
    path('updateactiv', views.updateactiv, name='updateactiv'),
    path('getsource', views.getsource, name='getsource'),
    path('adjustsold', views.adjustsold, name='adjustsold'),
    path('updatesleeptime', views.updatesleeptime, name='updatesleeptime'),
    path('updatewaketime', views.updatewaketime, name='updatewaketime'),
    path('addevents', views.addevents, name='addevents'),
    path('tree', views.tree, name='tree'),
    path('quran', views.quran, name='quran'),
    path('get_board_data/', nodeviews.get_board_data, name='get_board_data'),
    path('save_board/', nodeviews.save_board, name='save_board'),
    path('lastnodeid', nodeviews.lastnodeid, name='lastnodeid'),
    path("create_node/", nodeviews.create_node, name="create_node"),
    path("update_node/<int:node_id>/", nodeviews.update_node_position, name="update_node"),
    path('create_connection/', nodeviews.create_connection, name='create_connection'),
    path('update_connection/', nodeviews.update_connection, name='update_connection'),
    path('getnodedata', nodeviews.getnodedata, name='getnodedata'),
    path('updatenode', nodeviews.updatenode, name='updatenode'),
    path('updatelabel', nodeviews.updatelabel, name='updatelabel'),
    path('get_connected_nodes', nodeviews.get_connected_nodes, name='get_connected_nodes'),
    path('roadmaps', todoviews.roadmaps, name='roadmaps'),
    path('addexpectedmoney', views.addexpectedmoney, name='addexpectedmoney'),
    path('receiveexpectedmoney', views.receiveexpectedmoney, name='receiveexpectedmoney'),
    path('choose_package', views.choose_package, name='choose_package'),
    path('deleteexpectedmoney', views.deleteexpectedmoney, name='deleteexpectedmoney'),
    # path('addtobalance', views.addtobalance, name='addtobalance'),
    # path('addtobalance', views.addtobalance, name='addtobalance'),
    # path('addtobalance', views.addtobalance, name='addtobalance'),
    # path('addtobalance', views.addtobalance, name='addtobalance'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
