# Generated by Django 6.0.5 on 2026-06-12 19:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('events', models.TextField()),
                ('prayer', models.BooleanField(default=False)),
                ('fajr', models.BooleanField(default=False)),
                ('duhr', models.BooleanField(default=False)),
                ('asr', models.BooleanField(default=False)),
                ('maghrib', models.BooleanField(default=False)),
                ('isha', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('run', models.BooleanField(default=False)),
                ('coding', models.BooleanField(default=False)),
                ('quran', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('sick', models.BooleanField(default=False)),
                ('pushups', models.BooleanField(default=False)),
                ('freelancing', models.BooleanField(default=False)),
                ('mast', models.IntegerField(default=0)),
                ('sleep', models.TimeField(blank=True, default=None, null=True)),
                ('wake', models.TimeField(blank=True, default=None, null=True)),
                ('face', models.ImageField(blank=True, default=None, null=True, upload_to='faces/')),
                ('abs', models.ImageField(blank=True, default=None, null=True, upload_to='abss/')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('addon_type', models.CharField(choices=[('support', 'Support'), ('feature', 'Feature'), ('integration', 'Integration'), ('security', 'Security'), ('analytics', 'Analytics'), ('storage', 'Storage'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Additional price per month', max_digits=10)),
                ('emoji', models.CharField(default='⭐', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False, help_text='Must be purchased with subscription')),
                ('max_quantity', models.IntegerField(blank=True, help_text='Max quantity per subscription, null=unlimited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['addon_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('isfix', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Essance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('km', models.FloatField()),
                ('amount', models.FloatField()),
                ('qty', models.FloatField()),
                ('empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HostingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('shared', 'Shared Hosting'), ('vps', 'VPS'), ('dedicated', 'Dedicated Server'), ('cloud', 'Cloud')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_gb', models.IntegerField(help_text='Storage in GB')),
                ('bandwidth_gb', models.IntegerField(help_text='Bandwidth in GB')),
                ('max_users', models.IntegerField(blank=True, help_text='Max concurrent users, null=unlimited', null=True)),
                ('uptime_sla', models.DecimalField(decimal_places=2, default=Decimal('99.90'), help_text='Uptime SLA percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Inraisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
                ('rest', models.FloatField(default=0.0)),
                ('ignored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('type', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('imglink', models.TextField(blank=True, null=True)),
                ('videolink', models.TextField(blank=True, null=True)),
                ('ytlink', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='node_images/')),
                ('x', models.FloatField(default=100)),
                ('y', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outraisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='💻', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per month', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=500)),
                ('long', models.CharField(max_length=500)),
                ('ishelped', models.BooleanField(default=False)),
                ('isaccissible', models.BooleanField(default=False)),
                ('habitat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('raison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inraisons')),
            ],
        ),
        migrations.CreateModel(
            name='Moneyexpected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('raison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inraisons')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=2000)),
                ('color', models.CharField(default='#000', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='dashboard.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='dashboard.node')),
            ],
        ),
        migrations.CreateModel(
            name='Outbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('raison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.outraisons')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('client', 'Client')], default='client', max_length=20)),
                ('balance', models.FloatField(default=0.0)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('idnumber', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('idimage1', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('idimage2', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_type', models.CharField(blank=True, help_text='Type of business (e.g., Restaurant, Boutique, etc.)', max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('custom_software_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override base price if needed', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('is_auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dashboard.client')),
                ('hosting_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='dashboard.hostingplan')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dashboard.software')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'software', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='dashboard.subscription')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('suspended', 'Suspended'), ('resumed', 'Resumed'), ('cancelled', 'Cancelled'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('addon_added', 'Addon Added'), ('addon_removed', 'Addon Removed'), ('plan_changed', 'Plan Changed'), ('discount_applied', 'Discount Applied'), ('other', 'Other')], max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value as JSON', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value as JSON', null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dashboard.addon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='dashboard.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'addon')},
            },
        ),
    ]
