# Generated by Django 4.2.4 on 2023-09-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=500)),
                ('long', models.CharField(max_length=500)),
                ('ishelped', models.BooleanField(default=False)),
                ('isaccissible', models.BooleanField(default=False)),
                ('habitat', models.FloatField()),
            ],
        ),
    ]
