# Generated by Django 4.2.4 on 2023-12-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inraisons_outraisons_profile_outbalance_inbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('events', models.TextField()),
                ('prayer', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('run', models.BooleanField(default=False)),
                ('coding', models.BooleanField(default=False)),
                ('working', models.BooleanField(default=False)),
                ('freelancing', models.BooleanField(default=False)),
            ],
        ),
    ]
