# Generated by Django 4.2.4 on 2023-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sleep',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='wake',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
