# Generated by Django 4.2.4 on 2023-12-13 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_activity_sleep_activity_wake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
