# Generated by Django 4.2.4 on 2023-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idimage1',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idimage2',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idnumber',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
