# Generated by Django 4.2.4 on 2023-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_idimage1_profile_idimage2_profile_idnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pushups',
            field=models.BooleanField(default=False),
        ),
    ]
