# Generated by Django 4.2.4 on 2024-03-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_activity_pushups'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='abs',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='abss/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='face',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='faces/'),
        ),
    ]
