# Generated by Django 4.2.4 on 2024-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_activity_abs_activity_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sick',
            field=models.BooleanField(default=False),
        ),
    ]
