# Generated by Django 4.2.4 on 2024-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_activity_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='quran',
            field=models.BooleanField(default=False),
        ),
    ]
