# Generated by Django 4.2.4 on 2024-10-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('km', models.FloatField()),
                ('amout', models.FloatField()),
                ('qty', models.FloatField()),
            ],
        ),
    ]
