# Generated by Django 4.2.4 on 2024-10-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_essance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essance',
            old_name='amout',
            new_name='amount',
        ),
    ]
