# Generated by Django 4.2.4 on 2024-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_amout_essance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inraisons',
            name='rest',
            field=models.FloatField(default=0.0),
        ),
    ]
