# Generated by Django 4.2.4 on 2024-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_inraisons_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='essance',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
