# Generated by Django 4.2.4 on 2024-12-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_essance_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mast',
            field=models.BooleanField(default=False),
        ),
    ]
