# Generated by Django 4.2.4 on 2024-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_activity_mast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='mast',
            field=models.IntegerField(default=0),
        ),
    ]
