# Generated by Django 4.2.4 on 2025-04-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_activity_mast'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbalance',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
