# Generated by Django 4.2.4 on 2025-07-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_outbalance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbalance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outbalance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
