# Generated by Django 4.2.4 on 2025-09-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_inbalance_date_alter_outbalance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detective_nodes/')),
                ('x', models.FloatField(default=100)),
                ('y', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#000', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='dashboard.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='dashboard.node')),
            ],
        ),
    ]
