# Generated by Django 4.2.4 on 2025-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_node_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='node_images/'),
        ),
    ]
