# Generated by Django 4.2.4 on 2025-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_node_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
