# Generated by Django 4.2.4 on 2025-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
