# Generated by Django 4.2.4 on 2025-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='imglink',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
