# Generated by Django 4.2.4 on 2025-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='videolink',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='imglink',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
